server:
  # Uses the PORT provided by Railway, or defaults to 8081 if running locally
  port: ${PORT:8081}
  forward-headers-strategy: native
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  # --- DATABASE CONFIGURATION ---
  datasource:
    url: jdbc:postgresql://mainline.proxy.rlwy.net:43963/railway
    username: postgres
    password: EKzHpCQRDxslQJkakaovtfXkqQMLVtqz
    driver-class-name: org.postgresql.Driver

  # --- HIBERNATE / JPA SETTINGS ---
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # --- SECURITY / KEYCLOAK CONFIGURATION ---
  security:
    oauth2:
      client:
        # 1. THE PROVIDER (Where Keycloak lives)
        provider:
          keycloak:
            issuer-uri: https://keycloak-production-05ac.up.railway.app/realms/dannycodes

        # 2. THE REGISTRATION (Your App's Identity)
        registration:
          keycloak:
            provider: keycloak
            # IMPORTANT: You named this 'users' here.
            # Make sure the Client ID in Keycloak website is also named 'users' (not 'user')!
            client-id: users
            client-secret: Ji0TEg5C3mc0GrG2y2fz3I2ara4snbHP
            authorization-grant-type: authorization_code
            scope: openid,profile,email
